name: Main

on:
  push:
    paths:
      - '**.mgst'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: 初始化Python 3.11
        uses: actions/setup-python@v4
        with :
          python-version: "3.11"
      
      - name: 依据requirements下载库
        run: |
          pip install -r requirements.txt
          
      - name: 执行文件
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          python3 main.py

      - name: 打包地图
        run: |
          zip -r release.zip ./saves
